backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - name: workplaces
    label: Workplaces
    label_singular: Workplace
    folder: workplaces
    create: true
    fields:
      - name: title
        label: Title
      - name: role
        label: Role
      - name: link
        label: Link
        regex: (?:http|https)\:\/\/.+\..+
      - name: startDate
        label: Start Date
        widget: datetime
        timeFormat: false
        default: ""
      - name: endDate
        label: End Date
        widget: datetime
        timeFormat: false
        default: ""
        required: false
      - name: description
        label: Description
        widget: text
        required: false
      - name: current
        label: I currently work here
        widget: boolean
        default: false
  - name: projects
    label: Projects
    label_singular: Project
    folder: projects
    create: true
    fields:
      - name: title
        label: Title
      - name: description
        label: Description
      - name: image
        label: Image
        widget: "image"
      - name: imageSize
        label: Image Size
        widget: "number"
      - name: link
        label: Link
        regex: (?:http|https)\:\/\/.+\..+
      - name: startDate
        label: Start Date
        widget: datetime
        timeFormat: false
