backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: image, label: Image, widget: "image" }
      - { name: imageSize, label: Image Size, widget: "number" }
      - { name: link, label: Link, regex: (?:http|https)\:\/\/.+\..+ }
      - { name: startDate, label: Start Date, widget: "date" }
